//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictionaryType
    {
        public DictionaryType()
        {
            this.Dictionary = new HashSet<Dictionary>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsSystem { get; set; }
    
        public virtual ICollection<Dictionary> Dictionary { get; set; }
    }
}
