//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library_Literature
    {
        public Library_Literature()
        {
            this.Library_Book = new HashSet<Library_Book>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public int Year { get; set; }
        public string PublishingHouse { get; set; }
        public string MainAuthor { get; set; }
        public string AdditionalAuthors { get; set; }
        public bool IsDeleted { get; set; }
        public string Desqription { get; set; }
    
        public virtual ICollection<Library_Book> Library_Book { get; set; }
    }
}
