//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public int IdVremyaZanyatia { get; set; }
        public int NotificationType { get; set; }
        public string NotificationData { get; set; }
    
        public virtual Dictionary Dictionary { get; set; }
        public virtual User User { get; set; }
        public virtual VremyaZanyatia VremyaZanyatia { get; set; }
    }
}
