//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prepod_PrepodLikes
    {
        public int Id { get; set; }
        public int IdSotr { get; set; }
        public int IdUser { get; set; }
    
        public virtual Prepod_PrepodMeta Prepod_PrepodMeta { get; set; }
    }
}
