//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prepod_PrepodMeta
    {
        public Prepod_PrepodMeta()
        {
            this.Prepod_PrepodiCafedri = new HashSet<Prepod_PrepodiCafedri>();
            this.PrepodDiscipline = new HashSet<PrepodDiscipline>();
            this.Prepod_PrepodLikes = new HashSet<Prepod_PrepodLikes>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int DegreeId { get; set; }
        public bool IsDismissed { get; set; }
        public string Classroom { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Photo { get; set; }
    
        public virtual Dictionary Dictionary { get; set; }
        public virtual ICollection<Prepod_PrepodiCafedri> Prepod_PrepodiCafedri { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<PrepodDiscipline> PrepodDiscipline { get; set; }
        public virtual ICollection<Prepod_PrepodLikes> Prepod_PrepodLikes { get; set; }
    }
}
