//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SostavGrupp
    {
        public int Id { get; set; }
        public bool FlagVibil { get; set; }
        public int IdSpisGroup { get; set; }
        public int IdStud { get; set; }
        public int Podgroup { get; set; }
        public System.DateTime DateEdit { get; set; }
    
        public virtual SpisokGrupp SpisokGrupp { get; set; }
        public virtual Student_StudentMeta Student_StudentMeta { get; set; }
    }
}
