//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spezialnost_SpezialnostMeta
    {
        public Spezialnost_SpezialnostMeta()
        {
            this.SpezialRazdeliDisziplini = new HashSet<SpezialRazdeliDisziplini>();
            this.SpisokGrupp = new HashSet<SpisokGrupp>();
            this.Student_StudentMeta = new HashSet<Student_StudentMeta>();
        }
    
        public int Id { get; set; }
        public int IdSpez { get; set; }
        public int GodPostup { get; set; }
        public int IdFrmObuch { get; set; }
        public int SrokObuch { get; set; }
        public int IdPodrazd { get; set; }
        public int IdFak { get; set; }
        public int IdInst { get; set; }
    
        public virtual Dictionary FormObuchDictionary { get; set; }
        public virtual Dictionary PodrazdDictionary { get; set; }
        public virtual Dictionary FakDictionary { get; set; }
        public virtual Dictionary InstDictionary { get; set; }
        public virtual Spezialnost Spezialnost { get; set; }
        public virtual ICollection<SpezialRazdeliDisziplini> SpezialRazdeliDisziplini { get; set; }
        public virtual ICollection<SpisokGrupp> SpisokGrupp { get; set; }
        public virtual ICollection<Student_StudentMeta> Student_StudentMeta { get; set; }
    }
}
