//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpisokGrupp
    {
        public SpisokGrupp()
        {
            this.Nagruzka = new HashSet<Nagruzka>();
            this.Raspisanie = new HashSet<Raspisanie>();
            this.SostavGrupp = new HashSet<SostavGrupp>();
        }
    
        public int IdGroup { get; set; }
        public string Gruppa { get; set; }
        public int Pot { get; set; }
        public int KolPodGroup { get; set; }
        public int KolStud { get; set; }
        public Nullable<int> Kurs { get; set; }
        public int IdPodrazd { get; set; }
        public int IdSpezMeta { get; set; }
        public bool FlagVib { get; set; }
    
        public virtual Dictionary PotokDictionary { get; set; }
        public virtual Dictionary PodrazdDictionary { get; set; }
        public virtual ICollection<Nagruzka> Nagruzka { get; set; }
        public virtual ICollection<Raspisanie> Raspisanie { get; set; }
        public virtual ICollection<SostavGrupp> SostavGrupp { get; set; }
        public virtual Spezialnost_SpezialnostMeta Spezialnost_SpezialnostMeta { get; set; }
    }
}
