//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_StudentMeta
    {
        public Student_StudentMeta()
        {
            this.SostavGrupp = new HashSet<SostavGrupp>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int FacultyId { get; set; }
        public int IdSpecialtyMeta { get; set; }
        public int Pot { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public System.DateTime GraduationDate { get; set; }
        public bool IsDismissed { get; set; }
        public int MarkBookNumber { get; set; }
        public int StudentCardNumber { get; set; }
        public int FormOfStuduId { get; set; }
        public int GroupId { get; set; }
        public int SpecialtyId { get; set; }
        public int FlowId { get; set; }
    
        public virtual Dictionary FormObuchDictionary { get; set; }
        public virtual Dictionary FacultyDictionary { get; set; }
        public virtual Dictionary PotDictionary { get; set; }
        public virtual ICollection<SostavGrupp> SostavGrupp { get; set; }
        public virtual Spezialnost_SpezialnostMeta Spezialnost_SpezialnostMeta { get; set; }
        public virtual User User { get; set; }
        public virtual Dictionary Dictionary3 { get; set; }
        public virtual Dictionary Dictionary4 { get; set; }
        public virtual Dictionary Dictionary { get; set; }
        public virtual Spezialnost Spezialnost { get; set; }
    }
}
