//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Prepod_PrepodMeta = new HashSet<Prepod_PrepodMeta>();
            this.Student_StudentMeta = new HashSet<Student_StudentMeta>();
            this.UserMeta = new HashSet<UserMeta>();
            this.UserRole = new HashSet<UserRole>();
            this.UserTask = new HashSet<UserTask>();
            this.Notifications = new HashSet<Notification>();
            this.Library_History = new HashSet<Library_History>();
            this.Library_ReservateBook = new HashSet<Library_ReservateBook>();
            this.Library_ReservateBook1 = new HashSet<Library_ReservateBook>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> BlockDate { get; set; }
        public string BlockReason { get; set; }
        public bool IsDeleted { get; set; }
        public int ErrorPinCount { get; set; }
    
        public virtual ICollection<Prepod_PrepodMeta> Prepod_PrepodMeta { get; set; }
        public virtual ICollection<Student_StudentMeta> Student_StudentMeta { get; set; }
        public virtual ICollection<UserMeta> UserMeta { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
        public virtual ICollection<UserTask> UserTask { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Library_History> Library_History { get; set; }
        public virtual ICollection<Library_ReservateBook> Library_ReservateBook { get; set; }
        public virtual ICollection<Library_ReservateBook> Library_ReservateBook1 { get; set; }
    }
}
