//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VremyaZanyatia
    {
        public VremyaZanyatia()
        {
            this.Raspisanie = new HashSet<Raspisanie>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int Id { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual ICollection<Raspisanie> Raspisanie { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
