//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZaniatiaySemestr
    {
        public ZaniatiaySemestr()
        {
            this.Nagruzka = new HashSet<Nagruzka>();
        }
    
        public int IdZanSem { get; set; }
        public int IdUchPDisciplini { get; set; }
        public int Sem { get; set; }
        public int Chs { get; set; }
        public int IdVidaRabot { get; set; }
    
        public virtual ICollection<Nagruzka> Nagruzka { get; set; }
        public virtual SpezialRazdeliDisziplini SpezialRazdeliDisziplini { get; set; }
        public virtual VidiRabot VidiRabot { get; set; }
    }
}
