//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.SqlEFEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcademyDBEntities : DbContext
    {
        public AcademyDBEntities()
            : base("name=AcademyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Dictionary> Dictionary { get; set; }
        public virtual DbSet<DictionaryType> DictionaryType { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Nagruzka> Nagruzka { get; set; }
        public virtual DbSet<Prepod_PrepodiCafedri> Prepod_PrepodiCafedri { get; set; }
        public virtual DbSet<Prepod_PrepodMeta> Prepod_PrepodMeta { get; set; }
        public virtual DbSet<PrepodDiscipline> PrepodDiscipline { get; set; }
        public virtual DbSet<Raspisanie> Raspisanie { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleTask> RoleTask { get; set; }
        public virtual DbSet<SostavGrupp> SostavGrupp { get; set; }
        public virtual DbSet<Spezialnost> Spezialnost { get; set; }
        public virtual DbSet<Spezialnost_SpezialnostMeta> Spezialnost_SpezialnostMeta { get; set; }
        public virtual DbSet<SpezialRazdeliDisziplini> SpezialRazdeliDisziplini { get; set; }
        public virtual DbSet<SpisokGrupp> SpisokGrupp { get; set; }
        public virtual DbSet<Student_StudentMeta> Student_StudentMeta { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserMeta> UserMeta { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserTask> UserTask { get; set; }
        public virtual DbSet<VidiRabot> VidiRabot { get; set; }
        public virtual DbSet<VremyaZanyatia> VremyaZanyatia { get; set; }
        public virtual DbSet<ZaniatiaySemestr> ZaniatiaySemestr { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Library_Book> Library_Book { get; set; }
        public virtual DbSet<Library_EventType> Library_EventType { get; set; }
        public virtual DbSet<Library_History> Library_History { get; set; }
        public virtual DbSet<Library_Literature> Library_Literature { get; set; }
        public virtual DbSet<Library_ReservateBook> Library_ReservateBook { get; set; }
        public virtual DbSet<Prepod_PrepodLikes> Prepod_PrepodLikes { get; set; }
    }
}
