//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.SqlEFEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library_EventType
    {
        public Library_EventType()
        {
            this.Library_History = new HashSet<Library_History>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Library_History> Library_History { get; set; }
    }
}
