//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.SqlEFEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library_Book
    {
        public Library_Book()
        {
            this.Library_History = new HashSet<Library_History>();
            this.Library_ReservateBook = new HashSet<Library_ReservateBook>();
        }
    
        public int Id { get; set; }
        public int LitaratureId { get; set; }
        public string BookNumber { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Library_Literature Library_Literature { get; set; }
        public virtual ICollection<Library_History> Library_History { get; set; }
        public virtual ICollection<Library_ReservateBook> Library_ReservateBook { get; set; }
    }
}
