//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.SqlEFEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library_History
    {
        public int HistoryId { get; set; }
        public int UserId { get; set; }
        public int BookId { get; set; }
        public System.DateTime HistoryDate { get; set; }
        public int EventTypeId { get; set; }
    
        public virtual Library_Book Library_Book { get; set; }
        public virtual Library_EventType Library_EventType { get; set; }
        public virtual User User { get; set; }
    }
}
