//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.SqlEFEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prepod_PrepodiCafedri
    {
        public Prepod_PrepodiCafedri()
        {
            this.Nagruzka = new HashSet<Nagruzka>();
            this.Raspisanie = new HashSet<Raspisanie>();
        }
    
        public int Id { get; set; }
        public int IdSotr { get; set; }
        public int IdCafedri { get; set; }
        public double Stavka { get; set; }
        public int TipZanyatosti { get; set; }
    
        public virtual Dictionary CafdraDictionary { get; set; }
        public virtual Dictionary TipZanyatostiDictionary1 { get; set; }
        public virtual ICollection<Nagruzka> Nagruzka { get; set; }
        public virtual Prepod_PrepodMeta Prepod_PrepodMeta { get; set; }
        public virtual ICollection<Raspisanie> Raspisanie { get; set; }
    }
}
