//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.SqlEFEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prepod_PrepodLikes
    {
        public int Id { get; set; }
        public int IdSotr { get; set; }
        public int IdUser { get; set; }
    
        public virtual Prepod_PrepodMeta Prepod_PrepodMeta { get; set; }
    }
}
