//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.SqlEFEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spezialnost
    {
        public Spezialnost()
        {
            this.Spezialnost_SpezialnostMeta = new HashSet<Spezialnost_SpezialnostMeta>();
        }
    
        public int IdSpez { get; set; }
        public string Spezialnost1 { get; set; }
        public string Spez { get; set; }
        public string Shifr { get; set; }
        public string Qualification { get; set; }
    
        public virtual ICollection<Spezialnost_SpezialnostMeta> Spezialnost_SpezialnostMeta { get; set; }
    }
}
