//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUPPRB.SqlEFEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VidiRabot
    {
        public VidiRabot()
        {
            this.Raspisanie = new HashSet<Raspisanie>();
            this.ZaniatiaySemestr = new HashSet<ZaniatiaySemestr>();
        }
    
        public int Id { get; set; }
        public int IdRzdRab { get; set; }
        public string VidRaboti { get; set; }
        public string VidRabSokr { get; set; }
        public string VidRabAbbreviatura { get; set; }
        public double NormChas { get; set; }
        public bool Flag { get; set; }
        public string Primech1 { get; set; }
        public string Primech2 { get; set; }
    
        public virtual Dictionary RazdRabDictionary { get; set; }
        public virtual ICollection<Raspisanie> Raspisanie { get; set; }
        public virtual ICollection<ZaniatiaySemestr> ZaniatiaySemestr { get; set; }
    }
}
